### ISSUE TITLE
Set individual layout for each grid

### ISSUE THREAD

**Issue by webdevilopers** [ThaDafinser/ZfcDatagrid#106]
A common use case for grids - wheter you are using the *bootstrap* or the *jqgrid* renderer - is an additional footer row for a summary including totals.

There are two *jqgrid* features that are already included but currentely can not be achieved with the *ZfcDatagrid* configuration since some options on the *jqgrid* and the *cellattr* of its columns are not supported:
https://github.com/ThaDafinser/ZfcDatagrid/issues/102

Though the template / view script for the grid can be overriden this may only work for grids that will integrate the desired or *footerrow*. Or additional code in the template is required to handle all cases.

This would become pretty ugly.

We could improve the grid by adding an option to set an individual template for each grid.

This way every grid can be manipulated manually to work with almost every setup - even *jqgrid*s summary feature - an example for this is coming up.

What do you think about it, @ThaDafinser ?

**Comment by ThaDafinser** [comment]
You can set custom templates with this line
```php
$grid->getRenderer()->setTemplate('your-template')
```

It must be set for each renderer, since each renderer has its own template
