### ISSUE TITLE
Add multiple cellattr on column when using jqGrid

### ISSUE THREAD

**Issue by webdevilopers** [ThaDafinser/ZfcDatagrid#107]
This issue is based on issue https://github.com/ThaDafinser/ZfcDatagrid/issues/102.

A common _jqGrid_ feature is using _footerrow_ and setting _footerData_ to add totals to the grid.

Unfortunately I could not append any javascript to the grid to add this after the grid was generated.

Same for using _grouping_ for _summary_. The following demo requires setting attributes _summaryType_ and _summaryTpl_ on columns:

``` javascript
summaryType:'min', summaryTpl:'<b>Min: {0}</b>
```

http://trirand.com/blog/jqgrid/jqgrid.html

Of course creating your own template is a possible workaround. But mostly for only this one use case.

The _jqGrid_ _Columns_ view helper already has the possibility to set options:
https://github.com/ThaDafinser/ZfcDatagrid/blob/master/src/ZfcDatagrid/Renderer/JqGrid/View/Helper/Columns.php#L86-95

The _getter_ methods get their values from _\ZfcDatagrid\Column\AbstractColumn_.
It would make no sense to add _jqgrid_ typical options like _summaryType_ there.
Extending the abstract class to define a jqgrid _Column_ would be possible.
But using a global _setOptions_ methods maybe is a smarter solution. And the use the view helper to set an array with "allowed" values.

Another workaround is adding options to the _cellattr_:
https://github.com/ThaDafinser/ZfcDatagrid/blob/master/src/ZfcDatagrid/Renderer/JqGrid/View/Helper/Columns.php#L109-115

``` php
            /**
             * Cellattr
             */
            $rendererParameters = $column->getRendererParameters('jqGrid');
            if (isset($rendererParameters['cellattr'])) {
                $options['cellattr'] = (string) $rendererParameters['cellattr'];
            }
            if (isset($rendererParameters['summaryType'])) {
                $options['summaryType'] = (string) $rendererParameters['summaryType'];
            }
            if (isset($rendererParameters['summaryTpl'])) {
                $options['summaryTpl'] = (string) $rendererParameters['summaryTpl'];
            }  
```

Should we add an array of possible options to set for the _cellattr_ and add a method for _setCellAttributes()_ and _addCellAttributes_ instead of using the _$rendererParameters_?

**Comment by ThaDafinser** [comment]
This issue was moved to zfc-datagrid/zfc-datagrid#11
