### ISSUE TITLE
jqgrid paging breaks when using groupingView due to additional sortByColumns on POST request

### ISSUE THREAD

**Issue by webdevilopers** [ThaDafinser/ZfcDatagrid#108]
I added _groupingView_ to my jqgrid layout in order to add summary on my footerrow:

``` php
var grid_<?php echo $this->gridId; ?> = $('#<?php echo $this->gridId; ?>').jqGrid({
    // ...
    grouping: true,
    groupingView : {
        groupField : ['contract_id'],
        groupSummary : [true],
        groupColumnShow : [false],
        groupText : [' '],
        groupCollapse : false,
        groupDataSorted : false,
        groupSorted: false,
        //groupOrder: ['asc']
        //groupOrder: [false]
    groupOrder: []
    },    
    // ...    
```

The pagination will fail with a _500 Internal Server Error_ and the following message from _ZfcDatagrid_ on the POST request:
_Count missmatch order columns/direction_

The regular POST params without _groupingView_ will result in:

``` json
columnsGroupBy    
columnsHidden    id,contract_id
currentPage    2
isSearch    false
itemsPerPage    5
nd    1400510371968
sortByColumns    
sortDirections   
```

Using _groupView_ it will add the _sortByColumns_:

``` json
columnsGroupBy    
columnsHidden    id,contract_id
currentPage    2
isSearch    false
itemsPerPage    5
nd    1400510295168
sortByColumns    contract_id asc,
sortDirections 
```

I have tried several jqgrid _groupingView_ setups but could not override the _sortByColumns_.

This issue may be related to other issues and improvements:
- Issue https://github.com/ThaDafinser/ZfcDatagrid/issues/102
- Issue https://github.com/ThaDafinser/ZfcDatagrid/issues/107
- Issue https://github.com/ThaDafinser/ZfcDatagrid/issues/106

**Comment by ThaDafinser** [comment]
This issue was moved to zfc-datagrid/zfc-datagrid#12
