### ISSUE TITLE
Enable usage of userData option in jqgrid

### ISSUE THREAD

**Issue by webdevilopers** [ThaDafinser/ZfcDatagrid#109]
Currentely there is a way to enable the usage manually.

Override the layout script and add the *userData* to the global *data* and the add it to the *jsonReader*:
```php
var grid_<?php echo $this->gridId; ?> = $('#<?php echo $this->gridId; ?>').jqGrid({
    // ...

	footerrow: true,
	userDataOnFooter: true,

    datatype : 'local',

	<?php
		$data = $this->data;
                // Add your userData
		$userData = array('userdata' => array('my_summary_column' => 1000, 'my_column_to_show_label' => 'Totals'));
		$this->data = array_merge($data, $userData);
	?>
    
    data: {data: <?php echo json_encode($this->data); ?>},
	    
    jsonReader : {
        repeatitems : false,
        id : 'idConcated',

        //The current page
        page : function(data) {
            if (data.data) {
                return data.data.page;
            }
        },

        records : function(data) {
            if (data.data) {
                return data.data.records;
            }
        },

        total : function(data) {
            if (data.data) {
                return data.data.total;
            }
        },

        // Extending ZfcDatagrid for userData usage
        userdata : function(data) {
            if (data.data) {
                return data.data.userdata;
            }
        },

    // ...
});
```

Of course the *userData* should not be set inside the layout - at least unless individual templates aren't possible see issue https://github.com/ThaDafinser/ZfcDatagrid/issues/106.

Anyway we could add an *setUserData()* method to the *jqgrid* renderer that accepts a *phpArray* and add it to the global *data* and adapt it to the layout.

What do you think, @ThaDafinser ?

This issue may be related to the general improvement for setting *jqgrid* options see issue https://github.com/ThaDafinser/ZfcDatagrid/issues/102.

**Comment by ThaDafinser** [comment]
@webdevilopers is there something still needed? Or is it possible with `$grid->getRenderer()->setTemplate('your-template')`

**Comment by webdevilopers** [comment]
Sorry but I am no longer actively using the bundle.
