### ISSUE TITLE
Cannot inject custom formatter

### ISSUE THREAD

**Issue by webdevilopers** [ThaDafinser/ZfcDatagrid#111]
Though a column can use translation setting the `setTranslationEnabled()` method to true I need to translate my value inside a custom formatter.

This is more of _Question_ than an _Issue_.

Since this is my _DI_ attempt I tried to inject the `viewRenderer` into my custom formatter inside my `module.config.php`:

``` php
    'service_manager' => array(
        'factories' => [
            'ContractStateFormatter' => function($sm) {
                $viewRenderer = $sm->get('ViewRenderer');
                $contractStateFormatter = new \Application\Datagrid\Column\Formatter\ContractState();
                $contractStateFormatter->setView($viewRenderer);
                return $contractStateFormatter;
            }
        ]
    ),
```

Successfully setting the `formatter` on the `column`:

``` php
        $col = new Column\Select('state_name');
    $col->setLabel('State');
        $col->setWidth(5);
        $contractState = $this->getServiceLocator()->get('ContractStateFormatter');
        $col->setFormatter($contractState);
        #$col->setFormatter(new Formatter\ContractState()); // working fine
        $col->setFilterDefaultValue($state);
        $col->setTranslationEnabled(true);
        $grid->addColumn($col);
```

As you can see before the _DI_ the `formatter` was working fine.

Here is the `formatter`:

``` php
<?php
namespace Application\Datagrid\Column\Formatter;

use ZfcDatagrid\Column\Formatter\AbstractFormatter;
use ZfcDatagrid\Column\AbstractColumn;

class ContractState extends AbstractFormatter
{
    protected $validRenderers = array(
        'jqGrid',
        'bootstrapTable'
    );

    protected $view;

    public function setView($view)
    {
        #echo $view->translate('Home');        
        #$this->view = 'test';
        $this->view = $view;
    }

    public function getView()
    {
        return $this->view;
    }

    public function getFormattedValue(AbstractColumn $column)
    {
        $row = $this->getRowData();

$this->view->translate($row['state_name']));
        $html = sprintf('<span class="state_name">%s</span><br>', $row['state_name']); // translation getTranslator()
        // some custom formatting
        return $html;
    }
}
```

The setting works fine, the translation works fine. But though everything worked fine before I now get the following error:
**Could not save the datagrid cache. Does the directory "/home/.../Zend/workspaces/DefaultWorkspace10/PQ2/data/ZfcDatagrid" exists and is writeable?**

This actually makes no sense, right? Maybe the problem is caused by some kind of overhead or conflict with the `view` attribute. But I couldn't find any conflict inside the `formatter`.

Again, this is my first _DI_ attempt. Please tell me if my approach is wrong.
Thanks

**Comment by ThaDafinser** [comment]
This issue was moved to zfc-datagrid/zfc-datagrid#13
