### ISSUE TITLE
GridCell shows NaN when using formatter=number together with Type\Number

### ISSUE THREAD

**Issue by webdevilopers** [ThaDafinser/ZfcDatagrid#113]
My data contains decimal values from my database that I would like to show with `jqgrid` locale formatter number for locale **de**:
https://github.com/tonytomov/jqGrid/blob/master/js/i18n/grid.locale-de.js#L102
```javascript```
	number : {decimalSeparator:",", thousandsSeparator: ".", decimalPlaces: 2, defaultValue: '0,00'},
```

This is my column config using the `rendererParameter` setting **formatter** to **number**:
```php
$col = new Column\Select('workDuration_week');
$col->setLabel('Total');
$col->setRendererParameter('formatter', 'number'); 
$grid->addColumn($col);
```

Given from my `dataSource` is the value **11.50**. The grid shows **11,50** as expected.

Of course I would like to align the number that's why I add the *ZfcDatagrid\Column\Type\Number*:
```php
$col->setType(new Type\Number(NumberFormatter::DECIMAL, NumberFormatter::TYPE_DEFAULT, 'de_DE'));
```

Now the `gridcell` shows **NaN** for my **11.50** value. But it seems to work fine using data like **3.00** which correctely produces **3,00**!

I then removed the **formatter** and left the *Type\Number* only.

Now the **11.50** value is displayed as **11,5** with `align="right"`.

How come the `gridcell` become a **NaN** value? Since it is a javascript parsing problem it looks like `ZfcDataGrid` is incorrectely parsing the value for an **xx,5x* data value.

**Comment by ThaDafinser** [comment]
You cant use both formatters. Choose the Type\Number from ZfcDatagrid or that one from Jqgrid.

Since Type\Number converts the number to a string (local dependent) it will give errors in JS

You can align with this: https://github.com/ThaDafinser/ZfcDatagrid/blob/master/src/ZfcDatagrid/Column/Style/Align.php
