### ISSUE TITLE
bootstrap daterangepicker locale usage

### ISSUE THREAD

**Issue by webdevilopers** [ThaDafinser/ZfcDatagrid#114]
Currentely you can configure the `locale` parameter for the Bootstrap DaterangePicker this way:

``` php
'locale' => \Locale::getDefault(),
```

See https://github.com/ThaDafinser/ZfcDatagrid/blob/master/docs/Configuration.md
`locale`: (object) Allows you to provide localized strings for buttons and labels, and the first day of week for the calendars

According to the DaterangePicker `locale` exprects an object:
https://github.com/dangrossman/bootstrap-daterangepicker#options

E.g.:

``` php
'locale' => [
    'customRangeLabel' => 'Eigener Zeitraum'
],
```

Anyway this looks like the wrong place to translations especially when you are trying to add multiple languages.

Does the DaterangePicker offer a different attempt maybe in combination with `jQuery` itself or its `datepicker`?

**Comment by ThaDafinser** [comment]
This issue was moved to zfc-datagrid/zfc-datagrid#14
