### ISSUE TITLE
Search column filter text gets garbaged

### ISSUE THREAD

**Issue by ghiamar** [ThaDafinser/ZfcDatagrid#116]
Hi, Ihave implemeted ZfcDatagrid and is awesome, but I have a question.

If I write some text in a text column filter, lets say "wall", I get all "wall" items listed, but the text in the column filter input gets garbaged like this "~ \*wall\*"

Is there a way to get that column filter text cleaned before grid gets displayed?

Thanks!

**Comment by ThaDafinser** [comment]
@ghiamar @webdevilopers pls see #206
