### ISSUE TITLE
jqGrid: Custom-Filtering 

### ISSUE THREAD

**Issue by creifferscheid** [ThaDafinser/ZfcDatagrid#123]
Hey,
thanks for the great bundle, but I got stuck with a small bug?!

We want to use the jqGrid multipleSearch - function:

```
multipleSearch:true,
multipleGroup:true
```

But it doesn't work because the POST is different to a normal search-operation. 
This is a piece of POST Data using the multipleSearch-filtering

```
isSearch: true
filters:{"groupOp":"AND","rules":[{"field":"title","op":"cn","data":"ff"}]}
searchField:
searchString:
searchOper:
```

And for the simple Search

```
isSearch:true
title:fff
```

I think there's an error in the Renderer?

**Comment by ThaDafinser** [comment]
This issue was moved to zfc-datagrid/zfc-datagrid#16
