### ISSUE TITLE
Problem with select column

### ISSUE THREAD

**Issue by emontes** [ThaDafinser/ZfcDatagrid#130]
I have the following
$categories = array();
        foreach ($em->getRepository('Noticias\Entity\Category')->findBy(array(), array('title' => 'ASC')) as $item) {
            $categories[strval($item->getCatid())] = $item->getTitle();
        }
        $col = new Column\Select('catid','s');
        $col->setLabel('Categoría');
        $col->setReplaceValues($categories,false);
        $grid->addColumn($col);

But When I got the select I get:
<select name="toolbarFilters[s_catid]" style="width: 80%" onchange="this.form.submit()"><option value="" selected="selected">-</option><option value="0" selected="selected">Bacalar</option><option value="1">Cancún</option><option value="2">Caribe Mexicano</option><option value="3">Chetumal</option><option value="4">Cobá</option><option value="5">Cozumel</option><option value="6">El Estado</option><option value="7">Eventos</option><option value="8">Mexican Caribbean</option><option value="9">Playa del Carmen</option><option value="10">Política</option><option value="11">Puerto Morelos</option><option value="12">Riviera Maya</option><option value="13">Textos</option><option value="14">Tulum</option></select>

Where the values not correspond with the values in the array that I have sended, I have noticed that if I put some string in the array key then the Select goes right, but It don't correspond with the values for replace.

**Comment by ThaDafinser** [comment]
This issue was moved to zfc-datagrid/zfc-datagrid#17
