### ISSUE TITLE
ZfcDatagrid with Zend\Db\TableGateway Table

### ISSUE THREAD

**Issue by viceamiral** [ThaDafinser/ZfcDatagrid#138]
Hi,
First thank you for your module,
I saw the documentation and i used the bootstrapAction tutorial, but how can I display my USERS table from the db ?
<pre>
public function bootstrapAction ()
    {
        $data = array(
            array ('displayName' => 'Mohammad ZeinEddin'),
            array ('displayName' => 'John Wayne'),
            array ('displayName' => 'Oprah Winfrey')
        );
        $grid = $this->getServiceLocator()->get('ZfcDatagrid\Datagrid');
        $grid->setTitle('Minimal grid');
        $grid->setDataSource($data);
        $col = new Column\Select('displayName');
        $col->setLabel('Name');
        $grid->addColumn($col);
        $viewAction = new Column\Action\Button();
        $viewAction->setLabel('View');
        $viewAction->setLink('view/url/id');
        $viewAction->setAttribute('id' ,'5');
        $viewAction->setTitle('View Details');
        $actions = new Column\Action();
        $actions->setLabel('');
        $actions->addAction($viewAction);
        $actions->addAction($icon);

        $grid->addColumn($actions);

        $grid->render();
        return $grid->getResponse();
    }
</pre>

To display my USERS table I use this indexAction : 
<pre>
use Zend\Db\TableGateway\TableGateway;
public function indexAction()
    { 
		return new ViewModel(array('rowset' => $this->getUsersTable()->select()));
    }

public function getUsersTable()
	{
		// I have a Table data Gateway ready to go right out of the box
		if (!$this->usersTable) {
			$this->usersTable = new TableGateway(
				'users', 
				$this->getServiceLocator()->get('Zend\Db\Adapter\Adapter')
			);
		}
		return $this->usersTable;
	}
</pre>
I will be greatly appreciated if you give me your help, I'm starting to build my project and i need to display all my tables and to manage them using the edit and delete actions 
Please remember that I use only the Zend\Db NOT the Doctrine2/ORM.
I am waiting for your reponse, Sorry for my bad english

**Comment by ThaDafinser** [comment]
I close it for now. If someone sends a PR i will review it.

Since i'm using only array and Doctrine currently
