### ISSUE TITLE
Custom form for filtering

### ISSUE THREAD

**Issue by ghost** [ThaDafinser/ZfcDatagrid#142]
Hey,

is there a way to implement a form(zend-form) which offers the filter fields?

The way i got in my mind is:
-create a own renderer + layout/toolbar(or extend the bootstrap one)
-create the form and pass it from the renderer to the view
-implement the getFilter-Function in the renderer which handles the post-data and creates the Zfcdatagrid-Filter elements(?)

I dont want to handle the post-data in my controller and create a custom query for the grid...

Im using doctrine.
Great work by the way and greetings from Hamburg ;)

**Comment by imonteiro** [comment]
@daBlubb that would be amazing :+1: 

@ThaDafinser so, you handle the data by hand for every field? (check if it's LIKE, GREATER, etc.)
I'm also using custom form. Maybe I will copy Datagrid Filter and make something to process some string and return the operators and values.
Do you have something like this or another better approach?

**Comment by ThaDafinser** [comment]
This issue was moved to zfc-datagrid/zfc-datagrid#22
