### ISSUE TITLE
Add column does not work with array specification and QueryBuilder

### ISSUE THREAD

**Issue by olexp** [ThaDafinser/ZfcDatagrid#151]
There is a bug when I try to add column with array specification for QueryBuilder. It appears because of setSelect method run on created instance which switches selectPart1 and selectPart2 values.

thadafinser/zfc-datagrid (0.9.1)

To reproduce (in action):

``` php
        $em = $this->getServiceLocator()->get('doctrine.entitymanager.orm_default');
        $data = $em->getRepository('Application\Entity\Product')->createQueryBuilder('p');
        $grid = $this->getServiceLocator()->get('ZfcDatagrid\Datagrid');
        $grid->setTitle('Product');
        $grid->setDataSource($data);
        $grid->addColumn(array(
            'colType' => 'Select',
            'select' => array(
                'column' => 'name',
                'table' => 'p',
            ),
            'label' => 'Name',
        ));

        $grid->render();

        return $grid->getResponse();
```

Action failed with exception Doctrine\ORM\Query\QueryException

```
    [Semantical Error] line 0, col 7 near 'name.p p_name,': Error: 'name' is not defined.
    SELECT name.p p_name FROM Application\Entity\Product p
```

When I skip $key with 'select' value in foreach loop in Datagrid.php:652 everything works correctly.

**Comment by jonathangreco** [comment]
I think you inversed column and table values.

Column should be with 'p' value.
table should be with 'name' value.

This seems to work.

**Comment by olexp** [comment]
It seems you didn't read the example code. 'p' stands for 'Application\Entity\Product'. It couldn't be column. Also alias in exception (p_name) created for name.p should say that it is something wrong.

Let me explain what really happens in code.
This part of Datagrid.php works correctly:
```php
        if ('ZfcDatagrid\\Column\\Select' == $class) {
            if (! isset($config['select']['column'])) {
                throw new \InvalidArgumentException('For "ZfcDatagrid\Column\Select" the option select[column] must be defined!');
            }
            $table = isset($config['select']['table']) ? $config['select']['table'] : null;
            $instance = new $class($config['select']['column'], $table);
        } else {
```
and we have instance of Select in $instance. Few lines below it there is loop:
```php
        foreach ($config as $key => $value) {
            $method = 'set'.ucfirst($key);
            if (method_exists($instance, $method)) {
                if (in_array($key, $this->specialMethods)) {
                    if (! is_array($value)) {
                        $value = array(
                            $value,
                        );
                    }
                    call_user_func_array(array(
                        $instance,
                        $method,
                    ), $value);
                } else {
                    call_user_func(array(
                        $instance,
                        $method,
                    ), $value);
                }
            }
        }
```
When it comes to 'select' key the method 'setSelect' is triggered on $instance and that's where the values of table and column switched. setSelect is called with $value = array('column' => 'name', 'table' => 'p') that magically transforms to setSelect('name', 'p'). Order here is important and it could be changed in action ($grid->addColumn()) but executing method call like this is unsafe.

As I already wrote, skipping 'select' key in loop could help. The same result could be achieved by removing 'select' from $specialMethods. Don't know how this will affect the rest of the code.

**Comment by ThaDafinser** [comment]
This issue was moved to zfc-datagrid/zfc-datagrid#19
