### ISSUE TITLE
Can we make it use Ajax? Ajax Massactions and Ajax Filtering would be awsome!

### ISSUE THREAD

**Issue by isisis** [ThaDafinser/ZfcDatagrid#154]
First of all, thx for this nice Module. Some Ajax functionality would be really awesome.
Is it possible to send Ajax Massactions? If we send Ajax Massactions it's also a must-have to filter the grid and fill new data by Ajax without reloading the page. Otherwise the Ajax Massactions wouldn't make sense.

**Why?**
This could be used as an easy way to add X-to-Many relations on the edit page of an Entity. So the ajax grid could be rendered next to the form elements and would send the entities id with its massaction ajax request, without even beeing a form element.

**Even better solution!** 
If it's not too hard to implement would be a **ZfcDatagridFormElement**, which can also filter data by ajax. The ZfcDatagridFormElement won't send the data, but write all selections to a hidden form element, so all selected IDs would be sent with the form. The selected IDs could be stored in a multiselect I guess.

**Even more nice awesome stuff**
A **ZfcDatagridDoctrineFormElement** would be mega aswome. Just working as the other one I described, but can populate data to doctrine entities.

**Comment by ThaDafinser** [comment]
Hi @isisis if i understand it correctly u are describing three things: AJAX in general, mass actions and "crud" operations?

About AJAX (loading data/sending): This is possible, but not with current renderer.
You could easily create a new one with extending: https://github.com/ThaDafinser/ZfcDatagrid/blob/master/src/ZfcDatagrid/Renderer/AbstractRenderer.php

Crud operations wont get implemented here, but could move to a "own" repo if wanted. I dont want it to be in here, since it adds a lot of complexity.

Mass actions are currently not like i want them, they could be enhanced if needed.

**Comment by ThaDafinser** [comment]
The jqGrid uses "AJAX" already for data loading if paging to another page: https://github.com/ThaDafinser/ZfcDatagrid/blob/master/src/ZfcDatagrid/Renderer/JqGrid/Renderer.php#L160-L163

**Comment by isisis** [comment]
Hey @ThaDafinser, I was not thinking of "crud operations", but just making the grid behave as a form element.

Let's assume I want to edit an Entity "A", just the normal way in a ZF2 form. The Entity "A" has relation to entity "B" with 1.000.000 entries in DB. Now showing entity B in a select dropdown for example, like Doctrines EntitySelect does, is extremely ugly and bad performing.
I would like to use a Datagrid here instead of an entity select, to search for entities and add them to my form (into hidden select element).

You think I could realize something like that, based on ZfcDatagrid, or would you just go another approach?

**Comment by imonteiro** [comment]
Hi @ThaDafinser,
I'm also interested on this enhancement (AJAX). Do you some plan/roadmap/ideas?
Thanks

**Comment by isisis** [comment]
Hey @imonteiro check this out,
https://github.com/isisis/EbnkRichElement
Maybe it's enough for your requirements.

**Comment by ThaDafinser** [comment]
This issue was moved to zfc-datagrid/zfc-datagrid#20
