### ISSUE TITLE
Type\Number + Filter not working correctly with decimal numbers

### ISSUE THREAD

**Issue by isisis** [ThaDafinser/ZfcDatagrid#155]
When I use
$col->setType(new \ZfcDatagrid\Column\Type\Number());
Searching doesn't work anymore.

If I type in "12.99" without brackets, I'm getting a warning:

Warning: NumberFormatter::parse(): Number parsing failed in C:\xampp\htdocs\ebonikerp\vendor\thadafinser\zfc-datagrid\src\ZfcDatagrid\Column\Type\Number.php on line 181

If I type in "12,99" without brackets, which is the formate for my locale, there's no warning, but there's no result either. Seems like the query is searching for "12" instead of "12.99".

Is there an easy way to get this working? Would be nice, if I could search for "12,99" or "12.99" and get the same result.

**Comment by ThaDafinser** [comment]
The number is locale based since it uses the php intl library.

Can you debug your query, what kind of value gets there?

**Comment by isisis** [comment]
This is what I see in Zend Developer Tools

SQL SELECT COUNT(DISTINCT c0_.id) AS sclr0 FROM catalog_product c0_ LEFT JOIN catalog_product c1_ ON c0_.id = c1_.mainProduct_id WHERE c0_.price = ? OR c0_.price = ?
Params     0 => float(12)
    1 => float(99)
Types     0 => int(2)
    1 => int(2)
Time 0.14500904083252 

As I said, it's searching for the int value "12"

**Comment by isisis** [comment]
The other query looks like this:

     //SQL 
    SELECT c0_.id AS id0, c1_.id AS id1, c1_.name AS name2, c1_.sku AS sku3, c1_.price AS price4 
    FROM catalog_product c1_ LEFT JOIN catalog_product c0_ ON c1_.id = c0_.mainProduct_id 
    WHERE c1_.price = ? OR c1_.price = ? GROUP BY c1_.id LIMIT 15 OFFSET 0 

    //Params     
    0 => float(12)
    1 => float(99)
    //Types     
    0 => int(2)
    1 => int(2)

**Comment by isisis** [comment]
Input Filter Value: 12,99
Class: ZfcDatagrid\Filter
Line: 232
The variable $value has this value:
     Array ( [0] => 12 [1] => 99 )

Input Filter Value: 12.99
Class: ZfcDatagrid\Filter
Line: 232
The variable $value has this value:
     Array ( [0] => 12.99 )

Input Filter Value: 12
Class: ZfcDatagrid\Filter
Line: 232
The variable $value has this value:
     Array ( [0] => 12 )

Guess this is the reason. You're using the comma for something else and implode the string value. I didn't understand what it is for.

**Comment by ThaDafinser** [comment]
ahhhh :smile: 

i see...if a "comma" is used the values are seperated:
https://github.com/ThaDafinser/ZfcDatagrid/blob/master/src/ZfcDatagrid/Filter.php#L199

There needs to be a "pre-check" for numbers

**Comment by ThaDafinser** [comment]
Closed by the fix of @kokspflanze
