### ISSUE TITLE
Export Columns

### ISSUE THREAD

**Issue by imonteiro** [ThaDafinser/ZfcDatagrid#156]
Hi @ThaDafinser 

Actually the export feature select the columns <code>getColumnsToExport()</code> based on Column types. Sometimes, the columns to display are different than the export just because we want display a "preview" and give the ability to export all the information of the current selection.

What you do think about this?

##### Suggestion:
Function to set the columns to export:
<code>$grid->setColumnsToExport($column1, $column2, $column5);</code>

or select based on a column propriety:
<code>$column1->setExport(true);</code>

However, we keep the current strategy when we don't explicitly define the columns to export.

In addition, would be nice to have the ability to give a different column title when exporting:
<code>$column1->setExportTitle('TITLE');

Regards

**Comment by ThaDafinser** [comment]
@imonteiro you already can do that, but maybe not to "beautiful"

The reason why `getColumnsToExport()` check the Column\Type is, that not each Type can actually be exported in each renderer. E.g. Actions doesnt make sense.

E.g. i add a checkable icon on a pdf export like this.
```php
        if ($grid->getRendererName() == 'tcpdf') {
            $col = new Column\ExternalData('P');
            $col->setLabel('P');
            $col->setWidth(3);
            $col->setDataPopulation(new Column\DataPopulation\StaticValue('public/images/icons/16x16/selection.png'));
            $type = new Type\Image();
            $type->setResizeHeight(6);
            $col->setType($type);
            $grid->addColumn($col);
        }
```
There is also a `$grid->getRenderer()->isExport()` maybe that fits your needs?

About title i got some things since some time local...need to deploy soon the files :-)

**Comment by imonteiro** [comment]
@ThaDafinser I got it... but yes, it's now "beautiful".

For now I check the render name. And waiting for you deploy :)

**Comment by umeshjoshi** [comment]
Hi @ThaDafinser,
I have an issue on export regarding filters. I have set some custom filters, and these are working fine.
But when I am exporting data its only filtering column filters and leaving custom filters.
Can you please help me to export custom filtered data.

Thanks,

**Comment by ThaDafinser** [comment]
@imonteiro i think i wont add this to the core

An easy other solution could be:
```php
$col1 = new Column\Select(...);
$col2 = new Column\Select(...);

if ($grid->getRendererName() == 'tcpdf') {
    $grid->setColumns([$col1]);
} else{
    $grid->setColumns([$col1, $col2]);
}
```
