### ISSUE TITLE
Many to Many Strategy

### ISSUE THREAD

**Issue by imonteiro** [ThaDafinser/ZfcDatagrid#157]
Hi,

I have a Many to Many relationship and i don't know how to reach my goal. I have these tables:

#### document table
id | name
------------- | -------------
| 1  |   A      
| 2  |   B      

#### category table
 id | name | category_list_id
----|--------- | -------------
1  |   C1    |    1      
 2  |   C2    |    2      

#### document_category table
document_id | category_id
------------- | -------------
          1            |        1             
          1            |        2             

<code>document_id + category_id = unique</code>

Now I want to display all documents and additionally a column for each category list with the category value populated.

In my datagrid definition I can do a foreach to add column based on my category list table (not presented). To populate, should I try by query (I'm trying this, by so far without success) and use a select column type or there is better approach to do this.

Thanks

**Comment by ThaDafinser** [comment]
Wild out of my code, you can do it like this:

```php
$col = new Column\Select(new Expr\Select('
            (
                SELECT
                    GROUP_CONCAT(
                        CONCAT(
                            product.number,
                            \' \',
                            product.description
                        ),
                        \'~\',
                        product.id
                    )
                FROM LispLogbook\Entity\Entry as entry_product
                JOIN entry_product.products product
                WHERE
                    entry_product.id = entry.id
            )
        '), 'selectedProducts');
$col->setLabel('Products');
$col->setType(new Type\PhpArray());
```

**Comment by imonteiro** [comment]
@ThaDafinser Thanks, worked as expected.
