### ISSUE TITLE
An alias "zfdb_adapter" was requested but no service could be found

### ISSUE THREAD

**Issue by ellipee** [ThaDafinser/ZfcDatagrid#158]
hello, thank you for this module, i followed every step in the installation process. but i get this error "An alias "zfdb_adapter" was requested but no service could be found." 
Secondly i am wondering if there is a way to install multiple grid in one view.

**Comment by ThaDafinser** [comment]
Hello @ellipee thank you.

But there isn't any `zfdb_adapter` named service...can you post please the complete error message?

About multiple grids per view, please see https://github.com/ThaDafinser/ZfcDatagrid/issues/87

**Comment by ellipee** [comment]
sorry my bad, the zfdb_adapter error was not an issue or zfcdatagrid. i have fixed the problem. i did use the forward controller plugin, and i forward my grid view to a view with a form on it. 
the problem i have now is that when i click on the grid header name to sort the records the form on the same view gets submitted

**Comment by ThaDafinser** [comment]
@ellipee that's because you use the same action for form and datagrid right?

ZfcDatagrid always needs it's own action without any other things (export, sort, filtering, paging,....wont work else)

**Comment by ellipee** [comment]
ok thank you very much

**Comment by ellipee** [comment]
i think i will just have to go with yii framework since it is not as complicated as zf2. most especially it allows one to display grids, forms in the same view in a straight forward manner.

**Comment by ThaDafinser** [comment]
@ellipee ZF2 is more extensible like yii or symfony, thats why it's also harder to "understand".

Displaying forms and grids in the same view (file) is not the best way to go, but you can do that if you want.
