### ISSUE TITLE
Rest service integration

### ISSUE THREAD

**Issue by santiagocan** [ThaDafinser/ZfcDatagrid#160]
Hi,

I have a question
how can I integrate a rest services to ZfcDatagrid
my rest service returns a JSON object for example:

{
    "_links": {
        "self": {
            "href": "http://localhost/ramsal/nv7api/public/nom-grupo-concepto?page=1"
        },
        "first": {
            "href": "http://localhost/ramsal/nv7api/public/nom-grupo-concepto"
        },
        "last": {
            "href": "http://localhost/ramsal/nv7api/public/nom-grupo-concepto?page=1"
        }
    },
    "_embedded": {
        "nom_grupo_concepto": [
            {
                "id_grupo_concepto": "1",
                "nom_grupo_concepto":"Test",
                "id_usuario_alta": "0",
                "fecha_hora_alta": "0000-00-00 00:00:00",
                "id_usuario_edicion": null,
                "fecha_hora_edicion": null,
                "_links": {
                    "self": {
                        "href": "http://localhost/ramsal/nv7api/public/nom-grupo-concepto/1"
                    }
                }
            }
        ]
    },
    "page_count": 1,
    "page_size": 25,
    "total_items": 1
}

Thank you

Br,
Santiago can

**Comment by ThaDafinser** [comment]
@santiagocan if you already use rest, there is no reason to use ZfcDatagrid.

Just do it client side

**Comment by ThaDafinser** [comment]
(If you want to integrate the data into an existing datagrid ...thats another thing :smile: )
