### ISSUE TITLE
Renderer service was not found, please register it: "zfcDatagrid.renderer.bootstrap"

### ISSUE THREAD

**Issue by ellipee** [ThaDafinser/ZfcDatagrid#161]
i have no idea what is causing this error. need help please

**Comment by ThaDafinser** [comment]
@ellipee i think you didnt installed the Module correct.

Please check: https://github.com/ThaDafinser/ZfcDatagrid/blob/master/docs/02.%20Quick%20Start.md#installation

**Comment by ThaDafinser** [comment]
No feedback
