### ISSUE TITLE
Problem with count Pagination Oracle

### ISSUE THREAD

**Issue by FraGoTe** [ThaDafinser/ZfcDatagrid#162]
Hi I got this error using an oracle adapter:

I have the following problem in the file Zend\Paginator\Adapter\DbSelect;
```
   /**
     * Returns the total number of rows in the result set.
     *
     * @return int
     */
    public function count()
    {
        if ($this->rowCount !== null) {
            return $this->rowCount;
        }

        $select = clone $this->select;
        $select->reset(Select::LIMIT);
        $select->reset(Select::OFFSET);
        $select->reset(Select::ORDER);

        $countSelect = new Select;
        $countSelect->columns(array('c' => new Expression('COUNT(1)')));
        $countSelect->from(array('original_select' => $select));

        $statement = $this->sql->prepareStatementForSqlObject($countSelect);
        $result    = $statement->execute();

        $row       = $result->current();

        $this->rowCount = $row['c'];

        return $this->rowCount;
    }
```
$row['c'] is empty $result->current() returns $row['C'], 'C' in uppercase.

**Comment by ThaDafinser** [comment]
@FraGoTe since i cannot check Oracle currently, would it solve the problem to just change the `c` to uppercase?

**Comment by FraGoTe** [comment]
yes, but that is in my zend vendor directory. How should I correct that without break any component or a future update?

**Comment by ThaDafinser** [comment]
@FraGoTe seems to be fixed in ZF 2.4, see here: https://github.com/zendframework/zf2/blob/release-2.4.0rc1/library/Zend/Paginator/Adapter/DbSelect.php#L21

or commit https://github.com/zendframework/zf2/commit/054a6af353e2934f8f27d34e80b49b6739b45147

**Comment by FraGoTe** [comment]
ZF2.4 it's not an stable version, by now I'll extend the datasource.

**Comment by ThaDafinser** [comment]
Yeah that is a possible workaround i also do, when i need to wait for an upgrade :smile:

**Comment by FraGoTe** [comment]
FYI: https://github.com/FraGoTe/ZfcDatagrid-Oracle

**Comment by ThaDafinser** [comment]
Nice work! :+1:
