### ISSUE TITLE
Pagination

### ISSUE THREAD

**Issue by FraGoTe** [ThaDafinser/ZfcDatagrid#169]
any way to use setPageRange for pagination?

**Comment by kokspflanze** [comment]
hi, atm its not possible, but if you want you can add these feature in `Datagrid` line ~1009 [link to file](https://github.com/ThaDafinser/ZfcDatagrid/blob/master/src/ZfcDatagrid/Datagrid.php#L1009). if you need help i can do that too =)

**Comment by jonathangreco** [comment]
Hi, i did it that way in my controller : 

`$response` is my `$grid` after Column declaration, and data setted.

`````PHP
        $response->loadData();
        $response->getPaginator()->setPageRange(5);
        return $response->getResponse();

``````

**Comment by ThaDafinser** [comment]
@FraGoTe was that the solution? If not please feel to reopen :)
