### ISSUE TITLE
Datagrid with an array of result from a very old Database

### ISSUE THREAD

**Issue by jonathangreco** [ThaDafinser/ZfcDatagrid#176]
Hi,
I have 2 connections from my zf2 application. One is in doctrine2 ORM, the other is the old historic database (almost 20years history).

I have to provide csv and excel export with data from this database. But when i do this

````PHP
$qb ->select('*')
            ->from('orders', 'c')
            ->innerJoin('lines', 'cl', 'ON', 'c.id= cl.id')
            ->where('c.id= 3186416');
$sql = $qb->getQuery()->getDQL();
````
and i do a `fetchAll` on it, i get an `array` and set Datasource like this
````PHP
        $results = $toolbox->getDAO()->fetchAll($em, $sql, array());
        $dataSource = new PhpArray($results);
        
        $grid = $this->getServiceLocator()->get('ZfcDatagrid\Datagrid');
        $grid->setDataSource($dataSource);
````

From this array i can't find out how to create column (which type). And how to get a response for my users.

i tried to do this
`````PHP
$grid->addColumn(array(
            'colType' => 'array',// from Column\Type\PhpArray->getTypeName()
            'label' => 'code commande'
        ));
```````
But it seems i miss some point and the documentation does not explain it yet, maybe if i understand something i can update it for new users.

Thanks in advance

**Comment by ThaDafinser** [comment]
Hi.

i wouldn't recomment using the `PhpArray` type in this case.

What you should do is,
1) read all columns from your table
2) make a foreach loop, where u create a col (with type string e.g.) per column from the table
3) apply the data (u can still use * then)

**Comment by ThaDafinser** [comment]
```php
foreach($columDefFromDb as $colDef){
  $col = new Column\Select($colDef['index']);
  $col->setLabel($colDef['label']);
  $grid->addColumn($col);
}
```

**Comment by jonathangreco** [comment]
Thanks it'es much more clear for me.
