### ISSUE TITLE
Can we use a custom footer for bootstrapTable renderer

### ISSUE THREAD

**Issue by jonathangreco** [ThaDafinser/ZfcDatagrid#177]
Hi,

Everything is in the question can we custom the footer call (with pagination partial too).

I have to do a custom paginator, to let the user change the number of items shown.
And custom the view, css class ...

Can i do that ?

P.S : Your module is awesome by the way.

**Comment by jonathangreco** [comment]
I see there is some methods `setDefaultItemsPerPage` and `getDefaultItemsPerPage` to achieve this for the paginator. This point is cleared.

**Comment by ThaDafinser** [comment]
This issue was moved to zfc-datagrid/zfc-datagrid#21
