### ISSUE TITLE
Is there a way to send the $grid as a string to the view?

### ISSUE THREAD

**Issue by murparreira** [ThaDafinser/ZfcDatagrid#179]
In our project we need to create a view based on a layout. This layout contains several components, one of them being the grid. The thing is why we can't send the grid like a string to be plotted inside our views? Something like `return new ViewModel(['table' => $grid->getResponse()]);`  

There is a similar question like this made by other guy but i didn't understand the answer. What do you mean by using forwards/split actions?

In our case it is not for rendering more than one grid in our view. We just need to return a `ViewModel` with several parameters like lists, texts and stuff, along with the grid itself.

**Comment by ThaDafinser** [comment]
@murparreira because datagrid has multiple return types. Dependent on the user action if returns:
- the inital HTML
- the next page (maybe only as json ...eg. in jqgrid)
- a excel as download
- a pdf as download
- ...

thats why you need to keep it in one action
