### ISSUE TITLE
Error typehint array x ArrayObject in the \ZfcDatagrid\Column\Action\AbstractColumn 

### ISSUE THREAD

**Issue by euofulano** [ThaDafinser/ZfcDatagrid#181]
Hi,
congratulations for this module, It's usefull a lot.

I'm with problem below:

When I use the ZfcDatagrid with \Zend\Db\Sql\Select the php throws the error below:

![loja-dinap1](https://cloud.githubusercontent.com/assets/2581415/8441988/4d22723e-1f52-11e5-8856-9cb6441cc20e.png)

I noticed that this error is generated because the \ZfcDatagrid\Column\Action\AbstractColumn :: isDisplayed method has the following signature:
AbstractColumn :: isDisplayed (array $ row), but this case was passed to the ArrayAccess object method. 

I think it's a problem with the typehint defined in the method.

My suggestion is remove the typehint and check inside the method if argument $row is a array or ArrayObject. 

If it's a good ideia, I can generate a pull request for fix the problem, ok?

**Comment by ThaDafinser** [comment]
@euofulano i dont think that would be a good idea.
The problem is there are so many different object types which could be converted to array....this would be too much.

We need to convert the result earlier to an array.
I havent used `Zend\Db` since a while, but maybe you can try, where it needs to be converted. and then we can include it

**Comment by ThaDafinser** [comment]
@euofulano i just added a (array) conversion earlier, this should fix your problem.

Please checkout the latest version and if it's not fixed, please reopen this issue

**Comment by ThaDafinser** [comment]
see release https://github.com/ThaDafinser/ZfcDatagrid/releases

**Comment by euofulano** [comment]
Thank, I did a test and the problem is fixed.
