### ISSUE TITLE
Creating Mass Action with Button on Toolbar

### ISSUE THREAD

**Issue by ellipee** [ThaDafinser/ZfcDatagrid#182]
Hello, Please i need help creating checkbox column with an action button on the toolbar that when clicked will send the ids of the checked checkbox to my controller.

i read  issues #56 where a discussion on the implementation of mass action was brought forth. but i have no idea how i can get it to work.

**Comment by ThaDafinser** [comment]
This issue was moved to zfc-datagrid/zfc-datagrid#23
