### ISSUE TITLE
PDF Error when Image is inclusive

### ISSUE THREAD

**Issue by ellipee** [ThaDafinser/ZfcDatagrid#183]
My grid pdf export button showings this error "TCPDF ERROR: [Image] Unable to get image: ice.jpg" when my grid has image.

but when i remove the image column the pdf export runs fine.
please help me.
the image path is in : Public/Data/Uploads
but in my controller i put: '/Data/Uploads/

**Comment by ThaDafinser** [comment]
@ellipee for the web view you use the relative link.

But for image loading it needs the complete link (with http://myDomain.../.../ice.jpg)
or an absolute link

**Comment by ellipee** [comment]
please i dont know where to set the complete link, this is what i tried but it didnt work.
 
$col = new Column\Select('image', 'p');
        $col->setType(new Type\Image('image', 'p'));
        $col->setLabel('Photo');
        $col->setUserSortDisabled(false);
        //$col->setWidth(15);
        $imageFormatter = new Formatter\Image();
        $imageFormatter->setPrefix('http://ice/data/uploads/students/');
        $imageFormatter->setAttribute('style', 'width:30px;');
        $imageFormatter->setAttribute('class', 'liha');
        $col->setFormatter($imageFormatter);
        $grid->addColumn($col);

**Comment by ellipee** [comment]
i change the path of the image in TCPDF Config to
 define('K_PATH_IMAGES', 'http://ice/data/uploads/students/'); the error now changes to 
TCPDF ERROR: [Image] Unable to get the size of the image: student5.jpg

**Comment by ThaDafinser** [comment]
That sounds a lot better.
Change the settings to use Exceptions: https://github.com/tcpdf-clone/tcpdf/blob/master/config/tcpdf_config.php#L218

For some reason now the filesize cannot get fetched here: https://github.com/tcpdf-clone/tcpdf/blob/master/tcpdf.php#L6884

Is it maybe a permission problem?

**Comment by ellipee** [comment]
it gives me this message
 Notice: TCPDF ERROR: [Image] Unable to get the size of the image: student6.jpg in C:\websites\ice\vendor\thadafinser\zfc-datagrid\src\ZfcDatagrid\Renderer\TCPDF\Renderer.php on line 353\
                                                         and
Notice: Undefined property: TCPDF::$cell_margin in C:\websites\ice\vendor\tcpdf\tcpdf.php on line 5758
                                                          and
 Notice: Undefined property: TCPDF::$cell_padding in C:\websites\ice\vendor\tcpdf\tcpdf.php on line 5759

**Comment by ellipee** [comment]
My project is not online, i am using wampserver.

**Comment by ThaDafinser** [comment]
@ellipee thats not a question of online/offline. Permission problems can always happen.

Another idea is that your image is broken`?

**Comment by ellipee** [comment]
i have full permission, i have a feeling that the problem has to do with the image path. but i am absolutely helpless on how to solve this problem, i have been battling with this issue for 1 week now.

**Comment by ellipee** [comment]
i have also change different images but still the problem persist

**Comment by ThaDafinser** [comment]
@ellipee i cant help you any further. You need to debug your code now...

Check this: http://php.net/manual/en/debugger-about.php

**Comment by ellipee** [comment]
@ThaDafinser i finally did by appending the path in the TCPDF render file like this
 $link = 'http://ice/data/uploads/students/'.$row[$col->getUniqueId()];
 i know it is not the best way to do, but it solve by problem for now.

**Comment by ellipee** [comment]
forgive me for asking this in this issue.
i open an issue on how to create mass action, i totally have no idea on how to do it.
i tried use the checkbox column type but it did not render. 
Thank you very much for your patience with me.
