### ISSUE TITLE
String as number with PHPExcel

### ISSUE THREAD

**Issue by jonathangreco** [ThaDafinser/ZfcDatagrid#185]
Hi

I have a problem with the use `ZfcDatagrid\Column\Type`.

I have a function :

``` PHP
    /**
     * create a column type with number formatted depends on Locale
     * @param integer $locale
     * @return Type
     */
    public function getNumberFromLocale($locale)
    {
        $colType = new Type\Number(
            NumberFormatter::DECIMAL,
            NumberFormatter::TYPE_DEFAULT,
            $locale
        );

        return $colType;
    }
```

This method is called from my column maker

``` PHP`
// More declaration above
        $col = new Column\Select('totalDutyFree');
        $col->setLabel('Montant facturé HT');
        $col->setType($this->getNumberFromLocale('fr_FR'));
        $col->setWidth(5);
        $grid->addColumn($col);
//more declaration below
```

What I want is :
On my XLS document, my totaDutyFree column has to be with numbers not string, but Excel says to me that all my numbers are in string. From here i tried a lot of things to make this work, no luck !
below I explain what I got, during my tests.

When my locale is En_us, it works for numbers like 15.56 but not for 15 or 5,000
When my locale is fr_FR it works only when the result is more than 1000. And never work for 15,15 or 15.

I also test with a code snippet that cast to double those numbers before setting again my dataSource, because mySQL returns all numbers as string and I thought my problems comes from here.

I'm stuck here, anyone as an idea ?

**Comment by ThaDafinser** [comment]
@jonathangreco the type handline is currently now implemented in the Excel renderer.
All is currently just a string (regardless what you define) see here: https://github.com/ThaDafinser/ZfcDatagrid/blob/master/src/ZfcDatagrid/Renderer/PHPExcel/Renderer.php#L90

Any PR solving that is welcome :+1:

**Comment by jonathangreco** [comment]
@ThaDafinser 
Hi,
I tried some things on this line to make a PR but i'm not currently close to do this.
https://github.com/ThaDafinser/ZfcDatagrid/blob/master/src/ZfcDatagrid/Renderer/PHPExcel/Renderer.php#L90

We need to use when $col is instance of `\ZfcDatagrid\Column\Type\Number\` a 
 `PHPExcel_Cell_DataType::TYPE_NUMERIC`

OR play with `PHPExcel_Style_NumberFormat::FORMAT_NUMBER_00`

I tried to make this work but for now I just miss something. Maybe a do it wrong, probably..

I paste what I did, even it's not working.

```PHP
                if ($col->getType() instanceof \ZfcDatagrid\Column\Type\Number) {
                    $sheet->getCell($currentColumn . $yRow)->setValue($value);
                    $sheet->getCell($currentColumn . $yRow)
                    ->getStyle($currentColumn . $yRow)
                    ->getNumberFormat()
                    ->setFormatCode(
                        PHPExcel_Style_NumberFormat::FORMAT_NUMBER_00
                    );
                } else {
                    $sheet->getCell($currentColumn . $yRow)->setValueExplicit($value, PHPExcel_Cell_DataType::TYPE_STRING);
                }
````


Or a previous version also not working

```PHP

                if ($col->getType() instanceof \ZfcDatagrid\Column\Type\Number) {
                    $sheet->getCell($currentColumn . $yRow)->setValueExplicit($value, PHPExcel_Cell_DataType::TYPE_NUMERIC);
                } else {
                    $sheet->getCell($currentColumn . $yRow)->setValueExplicit($value, PHPExcel_Cell_DataType::TYPE_STRING);
                }
````

**Comment by ThaDafinser** [comment]
@jonathangreco i gone now a bit deeper into the code and know why i didnt done this :see_no_evil: 

Numers and Dates are changed to a user value in PrepareData: https://github.com/ThaDafinser/ZfcDatagrid/blob/ac1ed60b0070bb247382f52b726d8093cde29eca/src/ZfcDatagrid/PrepareData.php#L196

We need to use that value, since there could be prefixes / suffxes or special formats in it...

So we have as a result a "unpredicable" string....how shall we tell PHPExcel what part is the date/Number and format it correctly? :)

**Comment by ThaDafinser** [comment]
This issue was moved to zfc-datagrid/zfc-datagrid#24
