### ISSUE TITLE
setReplaceValues() for empty string or null replaced with ['' => '-']

### ISSUE THREAD

**Issue by amohammad** [ThaDafinser/ZfcDatagrid#186]
Hi,

When use ```setReplaceValues()``` method with empty string or null it overwritten with ```['' => '-']``` even if i used ```setFilterSelectOptions()``` with ```$noSelect = false``` the filtering for the null value doesn't work.

e.g 
```
$approval = new Column\Select('approval', 'shr');
        $approval->setLabel('Approval');
        $approval->setReplaceValues(array(
            '' => $this->translate('Pending'),
            '0' => $this->translate('Rejected'),
            '1' => $this->translate('Approved')
        ));
```
Pending don't appear in the the filter and i get "-" for the empty value.

**Comment by ThaDafinser** [comment]
@amohammad sry i cant solve that... you need to either replace they "Pending" key with a real value, or remove the dropdown filter.

Blanks should never be used for something, since many things like this grid or the HTML forms mean by blank "nothing"
