### ISSUE TITLE
Actions

### ISSUE THREAD

**Issue by excennfahnfah1976** [ThaDafinser/ZfcDatagrid#191]
I get this error. How can i fix it
Catchable fatal error: Argument 1 passed to ZfcDatagrid\Column\Action\AbstractAction::isDisplayed() must be of the type array, object given, called in .

thank you

**Comment by excennfahnfah1976** [comment]
have anayone this error.
Is this module good ?
or have i choose an other one

**Comment by ThaDafinser** [comment]
@excennfahnfah1976 is seems that you are having an object in the data result, which is not supported currently.

What type of object do you wanna display?

(If you provide better issue description helping is easier...)

**Comment by excennfahnfah1976** [comment]
Thank you for your response. i want to display action link:
               /* @var $dbAdapter \Zend\Db\Adapter\Adapter */
        $dbAdapter = $this->getServiceLocator()->get('Zend\Db\Adapter\Adapter');
        
        /* @var $grid \ZfcDatagrid\Datagrid */
        $grid = $this->getServiceLocator()->get('ZfcDatagrid\Datagrid');
        $grid->setUserFilterDisabled(true);
        $grid->setTitle('Persons');
        $grid->setDefaultItemsPerPage(5);
        $grid->setDataSource($this->getServiceLocator()->get('nfacatalog_category_service')->testingDataGrid(), $dbAdapter);
      
        $col = new Column\Select('category_name','cattrans');
        $col->setLabel('Name');
        //$col->setIdentity();
        $grid->addColumn($col); 
        
        $col3 = new Column\Select('language_id','cattrans');
        $col3->setLabel('language_id');
        //$col->setIdentity();
        $grid->addColumn($col3); 
 
        $col4 = new Column\Select('language_name');
        $col4->setLabel('language_name');
        //$col->setIdentity();
        $grid->addColumn($col4); 
        
        $col2 = new Column\Select('language_local');
        $col2->setLabel('language_local');
        //$col->setIdentity();
        $grid->addColumn($col2); 
$actions = new Column\Action();
$actions->setLabel('action label');
$actions->addAction($viewAction);
$grid->addColumn($actions);
.
.
.
$grid->render();
return $grid->getResponse()

**Comment by ThaDafinser** [comment]
@excennfahnfah1976 i cant help you with the information you provided.
I already told you above, that there seems to be a object in the data result. Please check the result or dump it.

Generally please try out some PHP debugging tools with that its easy to find the issue:
- xdebug - http://xdebug.org/
- phpdbg - http://phpdbg.com/

**Comment by ThaDafinser** [comment]
No feedback

**Comment by shinesoftware** [comment]
I have the same error. The problem is the "array object".
Check the line https://github.com/ThaDafinser/ZfcDatagrid/blob/3d31e3ba2761850d3295a6fbe6cbc08ad88a4388/src/ZfcDatagrid/Renderer/BootstrapTable/View/Helper/TableRow.php#L146 

The object sent is: 

    object(ArrayObject)#1209 (1) {
      ["storage":"ArrayObject":private] => array(8) {
        ["p_id"] => string(2) "10"
        ["p_name"] => string(13) "Tango Passion"
        ["p_address"] => string(0) ""
        ["p_createdat"] => string(15) "02/02/15, 23:17"
        ["p_updatedat"] => string(15) "02/02/15, 23:17"
        ["p_public"] => string(2) "Si"
        ["action"] => string(0) ""
        ["idConcated"] => string(2) "10"
      }
    }

This object is sent by this code:

        $dbAdapter = $this->adapter;
	$select = new Select();
    	$select->from(array ('p' => 'events'));
        $select->where(array('user_id' => $userId));
    	$grid->setDataSource($select, $dbAdapter);

I have solved just by casting the object in this way: 

    $row = (array)$row;

regards

**Comment by ThaDafinser** [comment]
@shinesoftware where did you call that cast? Can you give me the file/line number? Then we can add it

**Comment by shinesoftware** [comment]
@ThaDafinser between the line 145 and 146 I have wrote:

    $row = (array)$row;

do you need a pull request?

regards

**Comment by shinesoftware** [comment]
Yes I am using Zend\Db 
how have I to update the code by the composer?

regards

**Comment by ThaDafinser** [comment]
@shinesoftware yes, please try out the master. But be aware that there are BC break changes, which were merged there for 1.0 version.

**Comment by shinesoftware** [comment]
Now the grid works again! thanks. 

BC break changes???

**Comment by ThaDafinser** [comment]
E.g. setFormatter() has become setFormatters() (multiple now possible) and other small things (php version, ZF minimum version, ...) 

Autoloading only composer allowed and so on...

master is the development branch. I will release it in version 1.0

**Comment by shinesoftware** [comment]
Ok let me know when you publish a stable version.

thanks
