### ISSUE TITLE
export custom filtered data

### ISSUE THREAD

**Issue by umeshjoshi** [ThaDafinser/ZfcDatagrid#193]
Hi ,
I have an issue on export regarding filters. I have set some custom filters, and these are working fine.
But when I am exporting data its only filtering column filters and leaving custom filters.
Can you please help me to export custom filtered data.

Thanks,

**Comment by umeshjoshi** [comment]
can anyone please help me to resolve this?

**Comment by ThaDafinser** [comment]
You did not provide any single information, from where i could starting to help you.

Post your code and maybe we can help you.

**Comment by umeshjoshi** [comment]
thank you for your response.
Please find below my code:

                 
                 
                 
                 $request = $this->getRequest();
                $toolbarFilters =   $request->getPost('toolbarFilters');
          $columns = $toolbarFilters['column_list'];
          $name = $toolbarFilters['name'];
      
  $dbAdapter = $this->getServiceLocator()->get('Zend\Db\Adapter\Adapter');
          
    $select = new \Zend\Db\Sql\Select;
    $select->from(array('u' => 'contact_list'));
       if($name != '') 
       {
          
        $select->where(array('u.first_name'=>$name));
       }
    $dataGrid = $this->getServiceLocator()->get('zfcDatagrid');
    $dataGrid->setTitle('Minimal grid');
    $dataGrid->setDefaultItemsPerPage(3);
    $dataGrid->setDataSource($select, $dbAdapter);
    
    
    $column_list = array('id'=>'ID', 'first_name'=>'First Name','last_name'=>'Last Name', 'email'=>'Email', 'gender'=>'Gender');
  $dataGrid->setToolbarTemplateVariables(array('columnsList' =>  $column_list,'filteredColumn' => $columns));
    
  $style = new Style\BackgroundColor(array(
            200,
            200,
            200
        ));
     foreach ($column_list as $key=>$value)  {
      
       if(!empty($columns)){
  if(  in_array  ( $key ,  $columns )){
    $col = new Column\Select($key, 'u');
    $col->setLabel($value);
    $dataGrid->addColumn($col);
     }
       } 
     else
     {
          $col = new Column\Select($key, 'u');
          $style->addByValue($col, 'pradeep');
            $col->setLabel($value);
            $col->addStyle($style);
            $dataGrid->addColumn($col);
     }
           
  }
   $aa = new Column\Action\Button();
            $aa->setLabel('edit');
            $aa->setAttribute('class', 'edit')    ;
            $actions = new Column\Action();
$actions->setLabel('');
$actions->addAction($aa);

     $dataGrid->addColumn($actions);         
          $dataGrid->render();

    return $dataGrid->getResponse();  



==========================================================================
here I am using 'toolbarFilters' to access my custom filter data
Here everythig  is working fine in HTML report but when I am exporting data in excel or pdf, my custom filters are not working while zfcDatagrid inbuilt column filters are working fine.

Please have a look and let me know if I am missing any syntax.

Thank you.

**Comment by ThaDafinser** [comment]
This issue was moved to zfc-datagrid/zfc-datagrid#25
