### ISSUE TITLE
Auto suggestion

### ISSUE THREAD

**Issue by umeshjoshi** [ThaDafinser/ZfcDatagrid#199]
Hi, 
Is there any inbuilt functionality in zfcDatagrid to autosuggest column values in column filters?

**Comment by ThaDafinser** [comment]
@umeshjoshi currently not. I also not intend currently to implement this.

Maybe someone else is interested in this?

**Comment by kokspflanze** [comment]
you mean somethink like http://jqueryui.com/autocomplete/ as little extension for the filter?

**Comment by ThaDafinser** [comment]
Yep. I've done that some time ago for a internal datagrid.
But currently i'm not a fan anymore of this, if using this, it should only work with local data and not remote. So all data must be available local

**Comment by umeshjoshi** [comment]
Hi,
Thanks to all of your valuable feedbacks. 
@ThaDafinser - For the time being I have integrated it auto complete.js. it working on my local system . I am just passing an URL to make ajax call.

**Comment by ThaDafinser** [comment]
This issue was moved to zfc-datagrid/zfc-datagrid#26
