### ISSUE TITLE
Select filter isn't being set when a filter from the dropdown is selected

### ISSUE THREAD

**Issue by dannyhajj** [ThaDafinser/ZfcDatagrid#210]
The problem is here:
https://github.com/ThaDafinser/ZfcDatagrid/blob/master/view/zfc-datagrid/renderer/bootstrapTable/layout.phtml#L148

For example, if my array is:

```php
array(
    'red' => "Red",
    'green' => "Green",
)
```
If `red` was selected from the dropdown, `$col->getFilterActiveValue()` returns `red`.  But the problem is that it is comparing it to `sprintf($col->getFilterDefaultOperation(), $value)`, which is returning `= red` so the correct value doesn't get selected.

**Comment by dannyhajj** [comment]
I'd like to add that I had only test the bootstrap table.

**Comment by ThaDafinser** [comment]
@dannyhajj this value is only used on bootstrapTable currently so it should be fine (i merged it)
