### ISSUE TITLE
[Insight] Dependencies not installable

### ISSUE THREAD

**Issue by ThaDafinser** [ThaDafinser/ZfcDatagrid#214]
I don't know what's wrong here, but Scrutinizer works...

> SensioLabsInsight was not able to install your Composer dependencies. If you need to customize files or run commands to make it work, you can edit your SensioLabsInsight project configuration to override the default "pre_composer_script" and/or "post_composer_script" settings.

```
Loading composer repositories with package information


                                                                                                                         
  [Composer\Downloader\TransportException]                                                                               
  The &quot;https://packagist.org/packages.json&quot; file could not be downloaded: failed to open stream: Network is unreachable  
                                                                                                                         


update [--prefer-source] [--prefer-dist] [--dry-run] [--dev] [--no-dev] [--lock] [--no-plugins] [--no-custom-installers] [--no-autoloader] [--no-scripts] [--no-progress] [--with-dependencies] [-v|vv|vvv|--verbose] [-o|--optimize-autoloader] [-a|--classmap-authoritative] [--ignore-platform-reqs] [--prefer-stable] [--prefer-lowest] [packages1] ... [packagesN]



```

---------------------

_Posted from [SensioLabsInsight](https://insight.sensiolabs.com/projects/b4b135d7-4fe7-4dcd-ace3-f83003364d91/analyses/154)_

**Comment by kokspflanze** [comment]
looks like packagist was down?

**Comment by ThaDafinser** [comment]
Yep i think so...seems to be fixed now then rebuilding: https://insight.sensiolabs.com/projects/b4b135d7-4fe7-4dcd-ace3-f83003364d91/analyses/156
