### ISSUE TITLE
Add jqGrid specific colModel parameters

### ISSUE THREAD

**Issue by popovsergiy** [ThaDafinser/ZfcDatagrid#218]
I need several params **edittype**, **editoptions** and **searchoptions**

``` javascript
colModel: [
    //...
    {name: 'ship_via', width: 100, align: 'center', formatter: 'select',
        edittype: 'select',
        editoptions: {
            value: 'FE:FedEx;TN:TNT;IN:Intim',
            defaultValue: 'Intime',
            multiple: true
        },
        stype: 'select',
        searchoptions: {
            sopt: ['eq', 'ne'],
            value: 'FE:FedEx;TN:TNT;IN:Intim',
            attr: {multiple: 'multiple', size: 4},
            dataInit: dataInitMultiselect
        }},
    //...
],
```

but through ZfcDatagrid API I can only add **value** for **searchoptions** something like this
`$col->setFilterSelectOptions([/*values here*/])`.
In code on [#L103](https://github.com/ThaDafinser/ZfcDatagrid/blob/master/src/ZfcDatagrid/Renderer/JqGrid/View/Helper/Columns.php#L103) available only **clearSearch**, **defaultValue**, **stype** and **value**.
Is it possible add specific parameters for colModel?

**Comment by ThaDafinser** [comment]
I once added some options here: https://github.com/ThaDafinser/ZfcDatagrid/blob/804d0a83901cb3672e9aaac1a1f689d944e6be0c/src/ZfcDatagrid/Renderer/JqGrid/View/Helper/Columns.php#L92-L98
https://github.com/ThaDafinser/ZfcDatagrid/blob/804d0a83901cb3672e9aaac1a1f689d944e6be0c/src/ZfcDatagrid/Renderer/JqGrid/View/Helper/Columns.php#L167-L170

Maybe this should get more "general" for all options.

Maybe you can provide a PR for this?

**Comment by ThaDafinser** [comment]
This issue was moved to zfc-datagrid/zfc-datagrid#27
