### ISSUE TITLE
Implement object dereferencing for setters

### ISSUE THREAD

**Issue by popovsergiy** [ThaDafinser/ZfcDatagrid#221]
Since PHP 5.4 appears awesomeness "class member access on instantiation"

``` php
(new CoolObject())->setSomething($option)->addOther($item)->etc()
```

It would be very useful add something like this to your library:

``` php
$actions = new Column\Action('edit');
$actions->setLabel(' ');
$actions->setTranslationEnabled();
$actions->setFormatters([
    (new \ZfcDatagrid\Column\Formatter\Link())
        ->setAttribute('class', 'pencil-edit')
        ->setLink('/spares-ras/products/' . $fmtr->getColumnValuePlaceholder($colId))
]);
$grid->addColumn($actions);
```

**Comment by ThaDafinser** [comment]
@popovsergiy you mean the `fluent interface` ?
https://github.com/domnikl/DesignPatternsPHP/tree/master/Structural/FluentInterface

**Comment by popovsergiy** [comment]
@ThaDafinser, yes but you are called this differently :-)

**Comment by popovsergiy** [comment]
I meant call chain of methods
```php
(new \ZfcDatagrid\Column\Formatter\Link())
        ->setAttribute('class', 'pencil-edit')
        ->setAttribute('data-href', '/some/link')
        ->setLink('/other/link')
```

**Comment by jonathangreco** [comment]
I see your point.

In ZfcDatagrid, indeed, most of setters are not fluent (means that they don't return $this) you can't chain them.

Why not adding return $this.

**Comment by ThaDafinser** [comment]
This issue was moved to zfc-datagrid/zfc-datagrid#28
