### ISSUE TITLE
CSV file don't care about charset=utf-8 header

### ISSUE THREAD

**Issue by jonathangreco** [ThaDafinser/ZfcDatagrid#223]
Hi, I keep using your module to do some work, now my problem is with csv files, Excel does not want to open them in UTF-8.

As describe in this question : http://stackoverflow.com/questions/155097/microsoft-excel-mangles-diacritics-in-csv-files
Excel does not care about this Content-Type: 'text/csv; charset=utf-8', at all.

To set a csv file always openable with double click in UTF-8 we should add a "BOM UTF-8″  character.
0xEF, 0xBB, 0xBF like those.

Can we do that in our export class ? columns ? or it has to be done in the CSV Renderer class ?

**Comment by jonathangreco** [comment]
I propose a fix that do the job, in a fork of your repo. I don't know how this is working, if you can help.

**Comment by ThaDafinser** [comment]
@jonathangreco did you tried it with that fix?

Is that save with other programs as well?

**Comment by jonathangreco** [comment]
I tested with notepad, sublim texte, excel and notepad++ it worked for me

**Comment by ThaDafinser** [comment]
@jonathangreco thank you. Can you provider your fix as a PR? https://github.com/jonathangreco/ZfcDatagrid/commit/759f06bd7e37989414dfbd0afdfb16fefbe92cb0

Then your contribution is logged and i can merge it (plus the integration tests are run) :+1:

**Comment by ThaDafinser** [comment]
Just create a release with this fix
