### ISSUE TITLE
Wrong setMiddleToolbarTemplate description in documentation

### ISSUE THREAD

**Issue by shinesoftware** [ThaDafinser/ZfcDatagrid#224]
Hi, there is a problem in your documentation.
You talk about this method setMiddleToolbarTemplate but it doesn't exist. Please fix it.

Thanks

**Comment by ThaDafinser** [comment]
Removed. Thank you.

https://github.com/ThaDafinser/ZfcDatagrid/blob/master/docs/05.%20Toolbar%20and%20Custom%20Filtering.md
