### ISSUE TITLE
ServiceLocatorAwareInterface need to be removed and replaced by factories

### ISSUE THREAD

**Issue by jonathangreco** [ThaDafinser/ZfcDatagrid#233]
Since I make a fresh reinstall of zend framework with composer. I have now this error : 

Deprecated: ServiceLocatorAwareInterface is deprecated and will be removed in version 3.0, along with the ServiceLocatorAwareInitializer. Please update your class ZfcDatagrid\Datagrid to remove the implementation, and start injecting your dependencies via factory instead

**Comment by jonathangreco** [comment]
Ok I checked this pull request  Feature/mvc #232

**Comment by kokspflanze** [comment]
Hi, it should be fixed with https://github.com/ThaDafinser/ZfcDatagrid/pull/232  but i will check to remove the new dependencies

**Comment by jonathangreco** [comment]
I tried to update to dev-develop, and It seems i've no error due to ServiceLocator.

But i Don't know if it's because i had 0.11.0 version before, or due to new changes on this module and BC breaks but now when i wanna show my grid before export. My following code : 

`    public function getExportAction()
    {
       // SOme code with $id, and secure stuff

        if (!$question) {
            $this->flashMessenger()->setNamespace('danger')->addMessage('no_question_found');
            return $this->redirect()->toRoute('errorRoute');
        }
        // Set the grid
        $response = $this->todoListService->getWorkingTableFromQuestion($question);

        $response->setToolbarTemplateVariables(array('question' => $question));
        $response->loadData();

        $response->getPaginator()->setPageRange(5);
        return $response->getResponse();
    }`

My $response object has the data, and seems to be correct, but on the response page, no table is shown.

**Comment by kokspflanze** [comment]
can you test it with release [1.1.1](https://github.com/ThaDafinser/ZfcDatagrid/releases/tag/v1.1.1) please?

**Comment by ThaDafinser** [comment]
I published also a tag now for ZF 2.7
https://github.com/ThaDafinser/ZfcDatagrid/releases

**Comment by ThaDafinser** [comment]
Should be fixed with latest release

**Comment by jonathangreco** [comment]
Hi, my problem after update and tests is always here, and I discover why :

When I'm on my worktable page (with blue input for filtering and so on...) I have a blank page and my table is not showing up. I discover in the source code, that my table is fullfilled and hidden, because the 

code below doesn't have a width by default. If I had col-xs-12 class for example, then the table shows up. Do you have a solution for me without touching the ZfcDatagrid module or it's on your side ?

```HTML
<div class="table-responsive"> <!--  problem here no width -->
<table class="table table-striped table-bordered">
<thead>
<tbody>
<!-- All my data are correctly set here but hidden -->
</tbody>
</table>
</div>
```

**Comment by kokspflanze** [comment]
@jonathangreco did you use the latest bootstrap version? 3.3.7 or smth else?

**Comment by jonathangreco** [comment]
Your solution to override the layout is nice to me and will give a much more interresting solution than everything else. Thank you very much I'll try this right now, i give you feedback soon
