### ISSUE TITLE
Improvement: DataGridPluginManager for easy ZfcDatagrid configuration

### ISSUE THREAD

**Issue by popovsergiy** [ThaDafinser/ZfcDatagrid#240]
Hello, @ThaDafinser 
I use your module in my projects but it seem inconvenient create tons of Column objects through operator `new`. For these purpose I has created [module](https://github.com/agerecompany/zfc-data-grid) which extends possibility of ZfcDatagrid. These module include `DataGridPluginManager` which works like `FormElementManger` and also include Factory for create Column object through array configuration. You can see [tests](https://github.com/agerecompany/zfc-data-grid/blob/master/test/Column/Factory/ColumnFactoryTest.php) to better clarify the work of extension.
If you interested, I can build this in your module thereby expanding its capabilities.
What do you think?

**Comment by ThaDafinser** [comment]
@popovsergiy took me sadly way too long, to get back to your issue.

I would like to link to your project from the readme - can you therefor create in your project a readme to show the basic usage? After that i will update the readme here with an example and link

**Comment by ThaDafinser** [comment]
> If you interested, I can build this in your module thereby expanding its capabilities.

For now i would keep it seperate, since adding 2 modules is really easy, since we got composer for that job.
But like written above, i would like to link to your project.

**Comment by popovsergiy** [comment]
I am sorry. I split module into two, now DataGridPluginManager available [here](https://github.com/agerecompany/zfc-data-grid-plugin). README file also included.

**Comment by popovsergiy** [comment]
I am sorry. I split module into two, now DataGridPluginManager available [here](https://github.com/agerecompany/zfc-data-grid-plugin). README file also included.

**Comment by ThaDafinser** [comment]
I've create a link to your repo in the readme and the column docs.

https://github.com/ThaDafinser/ZfcDatagrid/blob/master/README.md#continue-with-your-own-datagrid
https://github.com/ThaDafinser/ZfcDatagrid/blob/master/docs/03.%20Columns.md#columns-introduction
