### ISSUE TITLE
Todo for 2.0

### ISSUE THREAD

**Issue by ThaDafinser** [ThaDafinser/ZfcDatagrid#249]
# Cleanup
## setRendererName()

The renderer is now set though the setRendererService() method, so this method has no affect anymore
https://github.com/ThaDafinser/ZfcDatagrid/blob/master/src/ZfcDatagrid/Datagrid.php#L789-L792
- [ ] remove the code
- [ ] update docs
- [ ] bc break (method removed)

**Comment by kokspflanze** [comment]
from my site we should also update all tests to use `::class` and not smth like https://github.com/ThaDafinser/ZfcDatagrid/blob/v1.3.0/tests/ZfcDatagridTest/DatagridTest.php#L160

we should also remove https://github.com/ThaDafinser/ZfcDatagrid/blob/v1.3.0/src/ZfcDatagrid/Datagrid.php#L1163
because of the changes of zend-mvc 2.7

**Comment by ThaDafinser** [comment]
Require PHP 7 + ZF3

**Comment by kokspflanze** [comment]
if we should only support PHP7, than we should also only support PHPUnit6 see https://github.com/sebastianbergmann/phpunit/issues/1751

**Comment by kokspflanze** [comment]
today i tried to set min PHP7 https://github.com/kokspflanze/ZfcDatagrid/tree/patch-5 the current problem i have is HHVM, 
- https://travis-ci.org/kokspflanze/ZfcDatagrid/jobs/175405597 with `hhvm.php7.all=1` in php.ini
- https://travis-ci.org/kokspflanze/ZfcDatagrid/jobs/175404812 with `"conflict": {"hhvm": "*"},` in composer.json

any one have a good idea expected `--ignore-platform-reqs` and remove hhvm from travis?

**Comment by ThaDafinser** [comment]
@kokspflanze i will get tomorrow back, where i will have some time to check the open issues and PR

**Comment by ThaDafinser** [comment]
@kokspflanze the solution seems to be this part
https://github.com/composer/composer/issues/4976

> I guess I'll just move hhvm to the allow_failures list at Travis and use --ignore-platform-reqs until HHVM's PHP 7 compatible.

**Comment by ThaDafinser** [comment]
This issue was moved to zfc-datagrid/zfc-datagrid#30
