### ISSUE TITLE
use of GROUP_CONCAT as a column and search

### ISSUE THREAD

**Issue by ZeinEddin** [ThaDafinser/ZfcDatagrid#25]
I am trying to use some custom doctrine 2 mysql function from https://github.com/beberlei/DoctrineExtensions like (GROUP_CONCAT), I am selecting it in a column, but it seems that the query is selecting the following:

``` php
a.group_concat(w.word) a_group_concat(w.word)
```

I am calling this by

``` php
$col = new Column\Standard('group_concat(w.word)', 'a');
```

and I am getting the following error:

``` php
[Syntax Error] line 0, col 33: Error: Expected Doctrine\ORM\Query\Lexer::T_FROM, got '('
```

am I doing something wrong? also how can I make this column searchable? will it produce any error?

**Comment by askaushish** [comment]
Do we have a option to chose having clause!

**Comment by ThaDafinser** [comment]
I think currently HAVING is not correctly supported.

I always use "subselects"

e.g with Doctrine

```php
        $col = new Column\Select(new Expr\Select('
            (
                SELECT
                    COUNT(address2)
                FROM MySpace\Entity\Group groupie2
                LEFT JOIN groupie2.members address2
                WHERE
                    groupie2.id = groupie.id
                GROUP BY groupie2.id
            )
        '), 'count_members');
        $col->setLabel('Members');
        $col->setWidth(15);
        $col->setUserFilterDisabled(true);
        $grid->addColumn($col);
