### ISSUE TITLE
Usage with Zend Expressive

### ISSUE THREAD

**Issue by lowtower** [ThaDafinser/ZfcDatagrid#256]
Hello,

can I use this module with zend expressive?
If yes, how can it be done!

Cheers,
LT.

**Comment by ThaDafinser** [comment]
@lowtower haven't used it with expressive until yet.

But i'm afraid it won't work out of the box, since the component rely on request/response in this way
https://github.com/ThaDafinser/ZfcDatagrid/blob/master/src/ZfcDatagrid/Datagrid.php#L60-L70
