### ISSUE TITLE
Error rendering NULLs in DateTime columns with PHPExcel

### ISSUE THREAD

**Issue by jroedel** [ThaDafinser/ZfcDatagrid#267]
I'm using v1.3.2. I'm exporting a DataGrid as an excel with some null values in a DateTime column.  I get the following Exception:
`Fatal error: Uncaught Error: Call to a member function setTimezone() on boolean in /var/www/test/vendor/thadafinser/zfc-datagrid/src/ZfcDatagrid/Renderer/PHPExcel/Renderer.php:112`

It seems that at some point the data source value of the datetime column NULL gets changed to a string(0) "". Then just before the Exception the Renderer tries to get cast the string(0)"" to a DateTime object.

I was able to reproduce the error in a ZF2 Controller (with the `?rendererType=PHPExcel` query param):
```
    public function testAction()
    {
    	$sm = $this->getServiceLocator();
    	/** @var $grid \ZfcDatagrid\Datagrid */
    	$grid = $sm->get('ZfcDatagrid\Datagrid');
    	$grid->setTitle('Test excel');
    	$grid->setDataSource([['testDate' => null]]);
    	$col = new \ZfcDatagrid\Column\Select('testDate');
        $dateType = new \ZfcDatagrid\Column\Type\DateTime('Y-m-d', \IntlDateFormatter::SHORT, \IntlDateFormatter::NONE);
        $col->setType($dateType);
        $col->setLabel('Test date');
        $grid->addColumn($col);
        return $grid->getResponse();
    }
```

I've been trying to figure out this problem on and off for the past month so I really appreciate whoever takes a look at this!

**Comment by ThaDafinser** [comment]
I will test this out today.
Had that issue once, but i think this is already fixed in master

**Comment by ThaDafinser** [comment]
@jroedel fix should be here https://github.com/ThaDafinser/ZfcDatagrid/pull/265

**Comment by ThaDafinser** [comment]
This issue was moved to zfc-datagrid/zfc-datagrid#32
