### ISSUE TITLE
Use route for links or action buttons

### ISSUE THREAD

**Issue by halfpastfouram** [ThaDafinser/ZfcDatagrid#268]
One thing I think the current version of the library is missing is the option to provide a route to the action buttons or link formatters.

Having to provide a string as a link or button target doesn't provide enough flexibility.

### Advantages
 - No need to generate route in controller, service or model and pass it to the grid.
 - A great way to generate routes with the option to fill the routes' parameters with the grid's column values.

### Requirements
 - Specify a link as a route.
 - Specify the column values required for building the route.
 - Routes will be generated when column action/select is rendered.

### Example

Route:
```php
'routes' => [
    'myRoute' => [
        'type'    => Segment::class,
        'options' => [
            'route'    => '/blog[/:month][/:id]',
            'defaults' => [
                'controller' => Controller\IndexController::class,
                'action'     => 'index',
                'month'      => 'september',
                'id'         => null,
            ],
        ],
    ],
];
````

Setting the link by route:
````php
$column->setRoute( 'myRoute' );
$column->setRouteParams( [
    'month' => $column->getColumnValuePlaceholder( 'month' ),
    'id'    => $column->getColumnValuePlaceholder( 'id' ),
] );
````

**Comment by ThaDafinser** [comment]
I like this idea.

To pass parameters there are currently only those 2 options:
```php
$action->setLink('/myLink/something/id/' . $action->getRowIdPlaceholder());
$action->setLink('/myLink/something/parameter1/' . $action->getColumnValuePlaceholder($grid->getColumnByUniqueId('my_col_id_parameter1')));
```

**Comment by kokspflanze** [comment]
check also [`ZfcDatagrid\Column\Formatter\GenerateLink`](https://github.com/ThaDafinser/ZfcDatagrid/blob/master/src/ZfcDatagrid/Column/Formatter/GenerateLink.php)

i added this long time ago, as example check https://github.com/kokspflanze/PServerAdmin/blob/master/src/PServerAdmin/Controller/DownloadController.php#L48-L55

**Comment by halfpastfouram** [comment]
@kokspflanze That looks ok but having to specify the `ViewRenderer` there feels wrong. Your solution just uses the view helper, which is only meant for usage in views. I'm going to look into a solution that doesn't require you to specify a `ViewRenderer` and will be a bit easier to use.

**Comment by ThaDafinser** [comment]
This issue was moved to zfc-datagrid/zfc-datagrid#33
