### ISSUE TITLE
Filters - Extended

### ISSUE THREAD

**Issue by imonteiro** [ThaDafinser/ZfcDatagrid#276]
Hi @ThaDafinser 

What do you think about these ideas, regarding the Filters:

- Possibility to extend Filter and create custom render to column filters (the class will return the html code for the BootstrapTable)
- Ability to add some callback in the Filter in order to apply custom filter

IM

**Comment by ThaDafinser** [comment]
This issue was moved to zfc-datagrid/zfc-datagrid#35
