### ISSUE TITLE
Cannot use ZfcDatagrid\Column\DataPopulation\Object as Object because 'Object'

### ISSUE THREAD

**Issue by kokspflanze** [ThaDafinser/ZfcDatagrid#283]
in php 7.2 we get following error

````
Cannot use ZfcDatagrid\Column\DataPopulation\Object as Object because 'Object'
````

looks like we have to rename that class.

for me personal `Phpobject` looks wrong to name it like that, but i have no other idea=(

**Comment by ThaDafinser** [comment]
This issue was moved to zfc-datagrid/zfc-datagrid#38
