### ISSUE TITLE
Searching new maintainer

### ISSUE THREAD

**Issue by ThaDafinser** [ThaDafinser/ZfcDatagrid#284]
Since i'm switching to a new job without ZF2 currently, i won't have much time/motivation to maintain this project anymore.

It would still be a good thing to keep the project running, since i think it helps some people getting some things faster done.

So is anyone of the past maintainers motivated to take over the lead?
@ZeinEddin @kokspflanze @imonteiro @manuscle @weckx @alessandropietrobelli @FraGoTe @webdevilopers 
(pinged all with >1 commits https://github.com/ThaDafinser/ZfcDatagrid/graphs/contributors)

Other possibility of course is always to fork the project - since it's under the MIT license...

**Comment by alessandropietrobelli** [comment]
@ThaDafinser thank you for the proposal, but I don't use ZF2 from a while.

**Comment by ZeinEddin** [comment]
I can take over this project, with some help from my work colleagues... as I am still working on a very long-term zf2 projects...

**Comment by webdevilopers** [comment]
Switched to a new job and Symfony some years ago. Sorry! Good luck!

**Comment by kokspflanze** [comment]
from my site i dont have a problem with it, or to do that job with someone else.

my personal projects are zf3 which using that module. i also have to support php7.2 soon

**Comment by ThaDafinser** [comment]
@ZeinEddin @kokspflanze thank you for the feedback!

I think best would be of course to have both in the boat, so a peer review is possible.
For now I gave both of you the collaborators permission.

If thats fine for you both, the question is if the repo shall be moved to another location as well?
Github is able to transfer it
![image](https://user-images.githubusercontent.com/533017/29700665-f4c153c2-8966-11e7-89d5-010fc124bae1.png)

**Comment by ThaDafinser** [comment]
Sure that possible.

In the new package just use https://getcomposer.org/doc/04-schema.md#replace

And i can do abandon the package https://stackoverflow.com/questions/40946151/marking-a-packagist-package-as-abandoned-in-favor-of-a-new-location?answertab=active#tab-top

**Comment by kokspflanze** [comment]
what about to create a organization with name zfcdatagrid and create there the repo with rights for @ThaDafinser , @ZeinEddin  and me? i think its better than to move it just to a person.

**Comment by ThaDafinser** [comment]
Of course a good option

**Comment by kokspflanze** [comment]
name it like `zfc-datagrid` or (same name for repo)? did you want to create it @ThaDafinser ?

today evening i would move everything to the new repo and set the packagist parts.

**Comment by FraGoTe** [comment]
Yes, I agree to move to an organization.

I'll try to help you guys but I'm not working with Zend Framework at this time.

**Comment by kokspflanze** [comment]
i started little todo list for the move https://github.com/ThaDafinser/ZfcDatagrid/pull/285

so everyone can follow

**Comment by imonteiro** [comment]
Hi everyone, I will try to help as a contributor.

**Comment by kokspflanze** [comment]
for moving the issues maybe @ThaDafinser can try https://github-issue-mover.appspot.com/ ? maybe that will help =)
