### ISSUE TITLE
Store parameters in session

### ISSUE THREAD

**Issue by manuscle** [ThaDafinser/ZfcDatagrid#60]
Is it possible to store sortBy, sortDirection & currentPage in session to retrieve them when back to the page?

**Comment by isisis** [comment]
@ThaDafinser It took me a while to find out, that I need to $grid->setCacheId('myId'); before I use this

        $cacheItem = $grid->getCache()->getItem($grid->getCacheId());
        if (is_array($cacheItem)) {
            $grid->getRenderer()->setFilters($cacheItem['filters']);
            $grid->getRenderer()->setSortConditions($cacheItem['sortConditions']);
            $grid->getRenderer()->setCurrentPageNumber($cacheItem['currentPage']);
        }

But it's not working correctly. The data result seems to be loaded from cache, but filters are empty however. Is it a bug or feature?

**Comment by lorenzoferrarajr** [comment]
Hi @manuscle,
I've tried to find a solution to this problem and I've been able to get things working using a delegator:

```php
namespace MyModule\Delegator;

use Zend\ServiceManager\DelegatorFactoryInterface;
use Zend\ServiceManager\ServiceLocatorInterface;
use Zend\Session\Container;
use Zend\Stdlib\Parameters;
use Zend\Http\PhpEnvironment\Request;
use Zend\Mvc\MvcEvent;

class DatagridDelegator implements DelegatorFactoryInterface
{
    public function createDelegatorWithName(ServiceLocatorInterface $serviceLocator, $name, $requestedName, $callback)
    {
        /** @var \ZfcDatagrid\Datagrid $datagrid */
        $datagrid = $callback();

        /** @var Request $request */
        $request = $serviceLocator->get('Request');

        $session = new Container(md5($request->getUriString()));

        if (!$session->offsetExists('postParameters')) {
            $session->postParameters = array();
        }

        if ($request->getMethod() == Request::METHOD_POST) {
            $session->postParameters = $request->getPost()->toArray();
        } elseif (count($session->postParameters) > 0) {
            $request = new Request();
            $request->setPost(new Parameters($session->postParameters));
            $request->setMethod('POST');
            $mvcEvent = new MvcEvent();
            $mvcEvent->setRequest($request);
            $datagrid->setMvcEvent($mvcEvent);
        }

        return $datagrid;
    }
}
```

In you config you should add:

```php
return array(
    'service_manager' => array(
        'delegators' => array(
            'ZfcDatagrid\Datagrid' => array(
                'MyModule\Delegator\DatagridDelegator'
            ),
        ),
    ),
);
```

**But this is code should be used carefully, and I would not use it in a production environment.**

The idea is simple (and full of bugs :bug::bug::bug:):

- If the page is loaded via POST method, save the post data in the session
- If the page is loaded via GET method:
  - create a new Request object
  - add to the request the post data previously saved in the session
  - set the request method to POST
  - add the request to a new MvcEvent
 -  set the MvcEvent in the $datagrid object

Now take a deep breath and forget what you just read. :) just kidding, but this code really is not ready for production (for example, I don't know if it works if used from cli).

I hope you can think of a better solution working on this.

**Comment by ThaDafinser** [comment]
This should now all be possible.

The cache is optional for export and GET is now also allowed. I dont think storing in session is then still needed, since you can just use browser history (when using GET)

**Comment by lorenzoferrarajr** [comment]
Great @ThaDafinser! Thank you for the update!
