### ISSUE TITLE
Filtering/Sorting without form?

### ISSUE THREAD

**Issue by bitworking** [ThaDafinser/ZfcDatagrid#89]
My question/issue is related to #60.

Why the decision to post a form for sorting/filtering the datagrid and not handle it thru GET parameters? Is it because of the routing?

I have the problem if I come back from a detail page (browser back button) I get the browser message "Erneute Formular-Übermittlung bestätigen". ("Confirm resubmitting of form").

**Comment by ThaDafinser** [comment]
Closed. Please see #207 just change in config the method: https://github.com/ThaDafinser/ZfcDatagrid/blob/17a5935f8102917779d6756be3794571a21c47f3/config/module.config.php#L67
