### ISSUE TITLE
Sub Queries and ZfcDatagrid

### ISSUE THREAD

**Issue by shinesoftware** [ThaDafinser/ZfcDatagrid#93]
Hi,
I would like to inform you that I have test the Select SubQuery feature in your module and seems to me that something doesn't work as well.

This is the subquery:

    // Get the TableGateway object to retrieve the data
    $dbAdapter = $this->getServiceLocator()->get('Zend\Db\Adapter\Adapter');

    // Check the Work Experiences of the user
    $sql = new Sql($dbAdapter);
    $subQry = $sql->select()->columns(array(new \Zend\Db\Sql\Expression('COUNT(*)')));
    $subQry->from('work_experiences');
    $subQry->where(array('personaldata_id' => 'pd.id'));
    $subQry->limit(1);

    // Get the user information and attach the sub query
    $mainselect = new Select();
    $mainselect->columns(array('weitems' => new \Zend\Db\Sql\Expression('?', array($subQry))));
    $mainselect->from(array ('pd' => 'personal_data'))
           ->join(array('c' => 'country'), 'pd.country_id = c.id', array('country'), 'left');

Column settings:

    $col = new Column\Select('weitems');
    $col->setLabel('First name');
    $grid->addColumn($col);

error returned:

    Statement could not be executed (42S22 - 1054 - Unknown column 'weitems' in 'field list')

returned Select query:

    SELECT (SELECT COUNT(*) AS Expression1 FROM "work_experiences" WHERE "personaldata_id" = 'pd.id' LIMIT '1') AS "weitems", "c"."country" AS "country" FROM "personal_data" AS "pd" LEFT JOIN "country" AS "c" ON "pd"."country_id" = "c"."id"

returned ZfcDatagrid:

    SELECT `pd`.`id` AS "pd_id", `pd`.`photo` AS "pd_photo", `pd`.`firstname` AS "pd_firstname", `pd`.`lastname` AS "pd_lastname", `c`.`country` AS "c_country", `pd`.`email` AS "pd_email", `pd`.`pac` AS "pd_pac", `pd`.`createdat` AS "pd_createdat", `pd`.`updatedat` AS "pd_updatedat", `pd`.`public` AS "pd_public" FROM "personal_data" AS "pd" LEFT JOIN "country" AS "c" ON "pd"."country_id" = "c"."id" ORDER BY "pd_createdat" DESC 

I need to select all the items in a foreign table "work_experiences" and count them. Then I would like to nest the result in the $mainselect.

Where I wrong?

thanks

**Comment by ThaDafinser** [comment]
No feedback
