### ISSUE TITLE
Specific renderer (currently only supported for jqGrid) not being rendered

### ISSUE THREAD

**Issue by webdevilopers** [ThaDafinser/ZfcDatagrid#95]
In my controller I set this rendererParameter:

``` PHP
        $col = new Column\Select('number', 'c');
        $col->setLabel('Number');
        //only jqGrid currently (custom display)
        $col->setRendererParameter('formatter', '
            function (value, options, rowObject) {
                // do something custom
                return "<b><u>" + value + "</u></b>";
            }
        ', 'jqgrid');        
        $grid->addColumn($col);
```

But it seems like the code is not generated inside the view as long as I don't remove the third parameter 'jqgrid'.

BTW: Is there a recommended way to escape the javascript?
I would recommend to put the javascript functions into the view and simply parse a string as second parameter so that jqgrid can use it to callback my view function.

Unfortunately parsing a string to the second parameter will cause the code to generate a string in double quotes:

``` javascript
{name: "c_number",index: "c_number",label: "Number",width: "5",hidden: false,sortable: true,search: true,formatter: "formatNumber"}],
```

But to make jqgrid use it as a callback the quotes need to be removed:

``` javascript
{name: "c_number",index: "c_number",label: "Number",width: "5",hidden: false,sortable: true,search: true,formatter: formatNumber}],
```

**Comment by ThaDafinser** [comment]
This issue was moved to zfc-datagrid/zfc-datagrid#7
