### ISSUE TITLE
Bootstrap DateRange not filtering correctely in examples

### ISSUE THREAD

**Issue by webdevilopers** [ThaDafinser/ZfcDatagrid#96]
_Example_: /zfcDatagrid/person/bootstrap

When using the DateRange picker on the _Birthday_ column no matter what value I choose I always get two rows returned with Birthday _31.01.1981_.

When using the DateRange picker on the _Last change" column with *Today_ or _Yesterday_ I always get the same rows returned.

Is there a special intl setting I have to set on DateRange or the column to make it work?

Ps.: Will there be a DateRange version available for _JqGrid_?

**Comment by askaushish** [comment]
Any solution to datepicker in phparray datasource

**Comment by ThaDafinser** [comment]
This issue was moved to zfc-datagrid/zfc-datagrid#8
