### ISSUE TITLE
Adding a simple style / class to column

### ISSUE THREAD

**Issue by webdevilopers** [ThaDafinser/ZfcDatagrid#99]
I havn't found any programmatic way to add a class name to i.e. an action button.
Currentely they have the Twitter Bootstrap 3 class "btn" attached. It would be nice to simply use:
```php
$column->addClassName('btn-primary');
```

**Comment by ThaDafinser** [comment]
Its now possible: https://github.com/ThaDafinser/ZfcDatagrid/pull/195
